<?php

/**
 * @file
 * Main module file.
 */

use Drupal\fluxservice\Plugin\Entity\AccountInterface;

/**
 * Implements hook_rules_category_info().
 */
function fluxfacebook_rules_category_info() {
  $info =  array();
  // Use the same icon as for the service plugin.
  $info['fluxfacebook'] = array(
    'label' => t('Facebook'),
  ) + fluxservice_get_service_icon_info('fluxfacebook');
  $info['facebook_object'] = array(
    'label' => t('Facebook: Object'),
  ) + fluxservice_get_service_icon_info('fluxfacebook');
  return $info;
}

/**
 * Implements hook_fluxservice_plugin_directory().
 */
function fluxfacebook_fluxservice_plugin_directory() {
  return 'lib/Drupal/fluxfacebook/Plugin';
}

/**
 * Implements hook_fluxfacebook_required_permissions().
 */
function fluxfacebook_fluxfacebook_required_permissions(AccountInterface $account) {
  return array(
    'manage_pages',
    'publish_stream',
    'user_status',
    'user_events',
    'user_groups',
    'friends_status',
    'read_stream',
  );
}
