<?php

/**
 * @file
 * Main module file.
 */

/**
 * Implements hook_rules_category_info().
 */
function fluxtwitter_rules_category_info() {
  $info =  array();
  // Use the same icon as for the service plugin.
  $info['fluxtwitter'] = array(
    'label' => t('Twitter'),
  ) + fluxservice_get_service_icon_info('fluxtwitter');
  $info['twitter_tweet'] = array(
    'label' => t('Twitter: Tweet'),
  ) + fluxservice_get_service_icon_info('fluxtwitter');
  $info['twitter_user'] = array(
    'label' => t('Twitter: User'),
  ) + fluxservice_get_service_icon_info('fluxtwitter');
  return $info;
}

/**
 * Implements hook_fluxservice_plugin_directory().
 */
function fluxtwitter_fluxservice_plugin_directory() {
  return 'lib/Drupal/fluxtwitter/Plugin';
}
