<?php
/**
 * @file
 * Hurricane tests.
 */

/**
 * Implements hook_menu().
 */
function hurricane_tests_menu() {
  return array(
    'hurricane/test' => array(
      'title' => 'Hurricane tests',
      'page callback' => 'drupal_get_form',
      'page arguments' => array('hurricane_tests_page'),
      'access arguments' => array('administer themes'),
      'type' => MENU_CALLBACK,
    ),
    'hurricane/autocomplete' => array(
      'title' => 'Hurricane dummy autocomplete',
      'page callback' => 'hurricane_tests_autocomplete',
      'access arguments' => array('administer themes'),
      'type' => MENU_CALLBACK,
    ),
  );
}

/**
 * Hurricane test page.
 */
function hurricane_tests_page($form, $form_state) {
  global $theme_key;
  $settings = hurricane_default_settings();

  if (count(hurricane_renderers()) < 2) {
    drupal_set_message(t('Looks boring? You did not activate any additional renderers. Go to your !modules page and active <em>hurricane_raphael</em> and <em>hurricane_spinjs</em>. For further instructions have a look at the<em>Installation</em> section in !readme.', array(
      '!modules' => l(t('modules'), 'admin/modules'),
      '!readme' => l(t('README.txt'), drupal_get_path('module', 'hurricane') . '/README.txt'),
    )), 'warning');
  }

  $configured = FALSE;
  foreach (array_keys($settings) as $key) {
    $value  = theme_get_setting('hurricane_' . $key, $theme_key);
    if ($value) {
      $configured = TRUE;
    }
  }

  if (!$configured) {
    drupal_set_message(t('You did not configure Hurricane in your current theme. Go to your !settings and have a look at the <em>Hurricane</em> sections.', array(
      '!settings' => l(t('themes settings page'), 'admin/appearance/settings/' . $theme_key),
    )), 'warning');
  }

  $form['button'] = array(
    '#prefix' => '<div id="hurricane-tests-ajax-wrapper">',
    '#suffix' => '</div>',
    '#type' => 'button',
    '#value' => t('Hit me!'),
    '#ajax' => array(
      'wrapper' => 'hurricane-tests-ajax-wrapper',
      'callback' => 'hurricane_tests_ajax_button',
    ),
  );
  $form['autocomplete'] = array(
    '#type' => 'textfield',
    '#title' => t('Autocomplete me!'),
    '#autocomplete_path' => 'hurricane/autocomplete',
    '#size' => 10,
  );
  $form['big'] = array(
    '#markup' => implode('', array(
        '<div class="ajax-progress hurricane-test-throbber">',
        '<div class="throbber"></div>',
        '</div>',
      )),
  );
  $form['#attached'] = array(
    'js' => array(
      drupal_get_path('module', 'hurricane_tests') . '/hurricane_tests.js',
    ),
    'css' => array(
      drupal_get_path('module', 'hurricane_tests') . '/hurricane_tests.css',
    ),
  );
  return $form;
}

/**
 * Ajax callback for dummy test button.
 */
function hurricane_tests_ajax_button($form, $form_state) {
  sleep(3);
}

/**
 * Dummy autocompletion to test spinner.
 */
function hurricane_tests_autocomplete() {
  sleep(3);
  drupal_json_output(array(
    'Drupal' => 'Drupal',
    'Is' => 'Is',
    'Awesome!' => 'Awesome!',
  ));
}
